### ISSUE TITLE
Project can't compile

### ISSUE THREAD

**Issue by Edwin97** [vv1ktor/SimonUI#1]
You did not commit SimonButton

**Comment by shayaansiddiqui** [comment]
SimonButton missing

**Comment by vv1ktor** [comment]
Hey,
Thanks for your issue, but this was a project I built merely to learn the basic concepts of SwiftUI and abandoned it soon after. With that said, I won't be maintaining this project; however, if you wish to "keep this project alive," you're more than welcome to create a pull request with the missing functionality. As of right now, I'm closing this issue. Reach out to me should you have any more questions.
